### ISSUE TITLE
Design a favicon

### ISSUE THREAD

**Issue by jbenito3** [reanahub/www.reana.io#2]
Once the logo is done, a favicon should be produced.

**Comment by tiborsimko** [comment]
Perhaps "ra" with r being printed in "reana red" and "a" in "reana-blue" colour?

**Comment by jbenito3** [comment]
Like this?

![favicon](https://user-images.githubusercontent.com/717470/46211215-49943c00-c333-11e8-81e4-766e3503c11b.png)
