### ISSUE TITLE
Review meta keywords

### ISSUE THREAD

**Issue by jbenito3** [reanahub/www.reana.io#3]
For the time being:
```
<meta name="keywords" content="reana, workflow, cwl, reuse, analysis, framework, research, data, software, virtual, machines, yadage, root, repository, cern, foss, open, software, search, python, api, rest, flask, docker, singularity">
```

**Comment by tiborsimko** [comment]
Some "reproducibility" and "preservation" would be good to add.

Some two-letter ones would be good to add.

See also GitHub topics at https://github.com/reanahub/reana such as "reusable science", "reproducible workflows", etc.
