### ISSUE TITLE
global: update broken links

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/www.reana.io#45]
After the migration from Read the Docs to docs.reana.io (https://github.com/reanahub/reana/pull/354, https://github.com/reanahub/reana-client/pull/421 ...) we many broken links, for example in [Get started](http://www.reana.io/#getstarted) the link after "Structure your analysis" points to the old reana.rtfd.io and the one after "Run your analysis" to reana-client.rtfd.io which has been simplified.

We should:
- Find all broken links
- Update them pointing to the new docs.reana.io

**Comment by tiborsimko** [comment]
It would be nice to add a link checker to CI procedures here, a bit as we are doing in `docs.reana.io`, so that we can catch these troubles early on.
