### ISSUE TITLE
roadmap: initial implementation

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/www.reana.io#47]
Create a new public roadmap page that would show what we are working on, what we plan to work on next, and what might be ahead in the future.

The big topics would be populated from our quaterly plans.  The details are not necessary to mention, they are listed as [REANA  GitHub projects](https://github.com/orgs/reanahub/projects) and triaged as "next" and "future" in the special [REANA triage board](https://github.com/orgs/reanahub/projects/7).

Examples for inspiration right from our corridor:
- https://about.zenodo.org/roadmap/
- https://inveniosoftware.org/roadmap/

**Comment by mvidalgarcia** [comment]
Some simple approaches. Please leave feedback.

a)
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/8863238/94006717-8e2b0480-fda0-11ea-8b55-d0cddf0af042.png">

b)
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/8863238/94007129-3fca3580-fda1-11ea-9cd4-d7c82bcdb4fc.png">

c)
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/8863238/94007188-612b2180-fda1-11ea-885b-b5fc65fff138.png">
