### ISSUE TITLE
gallery: possible add Launch-on-REANA badges

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/www.reana.io#72]
Note: similar to and depends on https://github.com/reanahub/reana-demo-helloworld/issues/60

Study whether we could nicely enrich gallery with "Launch-on-REANA" badges.

Beware about linking to the example sources vs launching examples.  The former is important, because the goal of gallery is to be educative and instructive. The latter is more of a secondary feature, to see the analysis in action.  Should come after people study examples.

So this issue concerns about changing the carousel design a bit to address both goals.  (A bit like empty launcher page showing a mini-gallery.)

Note: we can still keep linking examples to GitHub, to fulfil the education/instructive need first, and users will be able to launch workflows from there. In which case we don't have to do anything here.

**Comment by VMois** [comment]
I will share screenshots with a few possibilities. First one below:

(1) I have just added a badge underneath. Looks okay. Maybe the badge is a bit large.

![Screenshot 2022-04-19 at 12 25 02](https://user-images.githubusercontent.com/15694232/163984068-0d8369fd-7cef-4c1b-9e80-c92fad600e52.png)

**Comment by tiborsimko** [comment]
Looks nice. Perhaps you can try to also add a GitHub octocat logo just in front of "ATLAS BSM  search" _etc_ titles?

**Comment by VMois** [comment]
> ...try to also add a GitHub octocat logo just in front of "ATLAS BSM search" etc titles?

![Screenshot 2022-04-19 at 14 26 05](https://user-images.githubusercontent.com/15694232/164003253-3a552e49-f4ef-41ed-b708-504940248e23.png)

For me, personally, it looks too cluttered.

**Comment by tiborsimko** [comment]
Yeah, perhaps because this GitHub logo is very colourful and detailed one... What if you try the usual B/W shapy one, as people are used to it from the GitHub home page and that we also use on the workflow detailed page label?  As in Font Awesome: https://fontawesome.com/icons/github?s=brands

**Comment by VMois** [comment]
(1) If the icon is inside a link. In my opinion, not very nice. The GitHub logo is usually black in color and on a screenshot, it looks weird.

![Screenshot 2022-04-19 at 14 44 15](https://user-images.githubusercontent.com/15694232/164007346-0e05822e-876d-42e3-b949-05b6425d097c.png)

(2) The icon is outside the link. Looks more natural

![Screenshot 2022-04-19 at 14 45 50](https://user-images.githubusercontent.com/15694232/164008760-a1dfca98-521e-496c-bd65-c1472d931bed.png)

**Comment by audrium** [comment]
Just another idea to try: what if instead of using the badge we could use an icon like [this](https://fontawesome.com/v5/icons/external-link-alt?s=solid) next to the GitHub octocat logo? This would reduce the clutter, but could also be confusing for users..

P.S. I think that icons on the right side of the text would look better

**Comment by tiborsimko** [comment]
@VMois Yes, I think the last proposal with the icon outside the link looks good. (And it nicely mirrors the grey-on-lhs, red-on-rhs of the REANA badge!). I'd vote for that one.

@audrium Dunno about putting graphics on the right. Usually, it's a graphic plus a text in logos, headlines, etc. If we put the graphics on the right, then I'm afraid it might resemble more an emoticon style of expression than a label...

**Comment by VMois** [comment]
> what if instead of using the badge we could use an icon like [this](https://fontawesome.com/v5/icons/external-link-alt?s=solid) next to the GitHub octocat logo?

Do you mean some sort of an icon like a GitHub one? So people can click on it and the "Launch on REANA" page would open?

If we have such an icon styled for REANA, worth a try. One thing I am worried about is that it will be challenging to click on small icons near each other. Plus, "Launch on REANA" has  a meaning and even REANA-styled icon would not be descriptive for the visitor.

**Comment by VMois** [comment]
One thing more. Probably, it is not a good idea, but should we include "at CERN" in the badge?

![Screenshot 2022-04-19 at 15 39 31](https://user-images.githubusercontent.com/15694232/164016867-8c557033-a374-4b16-9370-a9cc607b254d.png)

**Comment by tiborsimko** [comment]
Yes, REANA@CERN indeed, in order to make it clearer upfront that people would need a CERN account.

**Comment by VMois** [comment]
Do we have any more ideas to try? If not, I will prepare PR for the latest above screenshot (with the "at CERN" part).
