### ISSUE TITLE
RFC project web site

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/www.reana.io#9]
REANA has been without a proper project web site for too long.

We have been musing on paper about the structure of the REANA project web site with sections permitting to learn what it is, see some examples, learn how to get started, and offer links to documentation, latest news, and social networks etc. The web site should be pleasing to various audiences  (researchers who would like only to use REANA, administrators who would like to install REANA on their computer centre, developers who would like to contribute).

Here is the web site representation prepared by @jbenito3:

![reanaio](https://user-images.githubusercontent.com/517546/40069038-69793626-586a-11e8-9caa-3eeff08c8f0e.png)

Are we happy with the ideas and with the prepared web site "as is"? Any suggestions regarding sections, content, style, colours, etc? 

P.S. See the web site in action at `www.reana.io`.  Note that we did not advertise the `www` subdomain yet, and note that `reana.io` currently does not point anywhere currently (because REANA domains were migrated to a different provider a few days ago) so we can easily change things still.  However we should not take too long either so that `reana.io` would reply something soon... Once we agree about the logo and the overall site look and feel, we can activate the redirections and still amend the site content later.

**Comment by hjhsalo** [comment]
I couldn't access www.reana.io, but the screenshot looks very good.

**Comment by diegodelemos** [comment]
Looks very good to me! From here we can start experimenting on new ideas such as adding a short description of what REANA is (thanks @ntarocco for the input). An example would be [Kubernetes](https://kubernetes.io/) website.
![screen shot 2018-05-16 at 9 03 35 am](https://user-images.githubusercontent.com/9035606/40103444-b8bd24e4-58ed-11e8-8259-cf6a36a972c4.png)

**Comment by ioannistsanaktsidis** [comment]
@jbenito3 looks great 😄 Very nice approach!

**Comment by tiborsimko** [comment]
> we can start experimenting on new ideas such as adding a short description of what REANA is

There is actually a short description, saying "Reproducible research data analysis platform", right below the logo. Perhaps it is too brief, but "less is more" :wink: The frugal description is also complemented/expanded by the four boxes below the slogan. We could improve the verbiage there...

**Comment by tiborsimko** [comment]
> I couldn't access www.reana.io

Inside-CERN only for now, after we finalise the logo we can open it up.

**Comment by suenjedt** [comment]
Very nice. I like the examples in the focus and that it's made with laugh (good to keep in mind!).  like the way the documentation is user group oriented. 
Minor detail: I dont understand why it is not "reproducible research analysis platform" (without data).

**Comment by tiborsimko** [comment]
The web site is now opened to the outside of CERN.
